[project]
name = "bjones-test"
version = "0.3.1"
description = "Simple test"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.11.12",
    "orjson>=3.10.15",
]

[tool.setuptools]
packages = []

[project.urls]

