name: Backward Compatibility Tests

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'CHANGELOG.md'
      - 'hello_world/**'

jobs:
  test-compatibility:
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for version comparison
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
    
    - name: Run backward compatibility tests
      run: |
        pytest tests/test_backward_compatibility.py -v
    
    - name: Check test coverage
      run: |
        pytest --cov=hello_world --cov-report=term-missing tests/test_backward_compatibility.py
