name: Build and Package Library
permissions:
  contents: write
  id-token: write
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 
      uses: actions/setup-python@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Build the artifact in dist/
      run: uv build
