name: Build and Package Library
permissions:
  contents: write
  id-token: write
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 
      uses: actions/setup-python@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Build the artifact in dist/
      run: uv build

    - name: Release to Github
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: | 
          dist/*.whl
          dist/*.tar.gz
        draft: ${{ contains(github.ref, 'beta') }}
        prerelease: ${{ contains(github.ref, 'beta') }}
        name: ${{ contains(github.ref, 'beta') && format('Beta Release {0}', github.ref_name) || github.ref_name }}
        body: ${{ contains(github.ref, 'beta') && 'This is a beta release and is not production ready.' || '' }}

    - name: Publish to TestPyPI
      if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'beta')
      run: uv publish --repository-url https://test.pypi.org/legacy/

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'beta')
      run: uv publish
      