name: Check and Publish

on:
  push:
    branches:
      - main

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        id: check
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"Merge pull request"* ]] && \
             [[ "${{ github.event.head_commit.message }}" == *"release-v"* ]]; then
            echo "is_release_merge=true" >> $GITHUB_OUTPUT
            if [[ "${{ github.event.head_commit.message }}" == *"Beta Testing"* ]]; then
              echo "release_type=beta" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.head_commit.message }}" == *"Release Candidate"* ]]; then
              echo "release_type=rc" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.head_commit.message }}" == *"Release"* ]]; then
              echo "release_type=stable" >> $GITHUB_OUTPUT
            else
              echo "release_type=none" >> $GITHUB_OUTPUT
            fi
          else
            echo "is_release_merge=false" >> $GITHUB_OUTPUT
            echo "release_type=none" >> $GITHUB_OUTPUT
          fi

      - name: Trigger beta publish workflow
        if: steps.check.outputs.is_release_merge == 'true' && steps.check.outputs.release_type == 'beta'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-pre-release.yml',
              ref: context.ref,
              inputs: {
                is_release_merge: '${{ steps.check.outputs.is_release_merge }}',
                release_type: '${{ steps.check.outputs.release_type }}'
              }
            })

      - name: Trigger RC publish workflow
        if: steps.check.outputs.is_release_merge == 'true' && steps.check.outputs.release_type == 'rc'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-rc.yml',
              ref: context.ref,
              inputs: {
                is_release_merge: '${{ steps.check.outputs.is_release_merge }}',
                release_type: '${{ steps.check.outputs.release_type }}'
              }
            })

      - name: Trigger stable publish workflow
        if: steps.check.outputs.is_release_merge == 'true' && steps.check.outputs.release_type == 'stable'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-stable.yml',
              ref: context.ref,
              inputs: {
                is_release_merge: '${{ steps.check.outputs.is_release_merge }}',
                release_type: '${{ steps.check.outputs.release_type }}'
              }
            }) 
