name: Check for Release Merge Event

on:
  push:
    branches:
      - main

jobs:
  check-for-release-merge:
    # Only run if this is a merge from a release branch
    if: |
      contains(github.event.head_commit.message, 'Merge pull request') &&
      contains(github.event.head_commit.message, 'release-v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit message and trigger appropriate workflow
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          
          if [[ "$COMMIT_MSG" == *"Beta Testing"* ]]; then
            echo "Triggering beta release workflow"
            gh workflow run publish-pre-release.yml
          elif [[ "$COMMIT_MSG" == *"Release"* ]]; then
            echo "Triggering stable release workflow"
            gh workflow run publish-release.yml
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
