name: Create beta Release Branch

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Branch to create beta release from'
        required: true
        default: 'main'

jobs:
  create-beta-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(grep -Po '(?<=version = ")[^"]+' pyproject.toml)
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Calculate beta version
        id: calc_version
        run: |
          IFS='.' read -r -a version_parts <<< "${{ steps.current_version.outputs.version }}"
          ((version_parts[1]++))
          version_parts[2]=0
          NEW_VERSION="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create and push beta release branch
        run: |
          NEW_VERSION="${{ steps.calc_version.outputs.new_version }}"
          BRANCH_NAME="beta-release-v$NEW_VERSION"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

      - name: Release to Github
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: ${{ contains(github.ref, 'beta') }}
          prerelease: ${{ contains(github.ref, 'beta') }}
          name: ${{ contains(github.ref, 'beta') && format('Beta Release {0}', github.ref_name) || github.ref_name }}
          body: ${{ contains(github.ref, 'beta') && 'This is a beta release and is not production ready.' || '' }}

      - name: Publish to TestPyPI
        if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'beta')
        run: uv publish --repository-url https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'beta')
        run: uv publish
