name: Create Pre-release

# Manual trigger for alpha/beta releases
on:
  workflow_dispatch:
    inputs:
      previous_version:
        description: 'Previous version (e.g., 0.3.28)'
        required: true
      release_type:
        description: 'Type of pre-release'
        required: true
        type: choice
        options:
          - beta
          - alpha
      bump_type:
        description: 'Type of version bump (major, minor, patch)'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout code without history to speed up workflow
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # Install dependencies
      - name: Install dependencies
        run: uv sync --all-extras --dev

      # Generate new version
      - name: Generate new version
        id: version
        run: |
          # Get previous version and bump type from inputs
          PREV_VERSION="${{ github.event.inputs.previous_version }}"
          BUMP_TYPE="${{ github.event.inputs.bump_type }}"
          RELEASE_TYPE="${{ github.event.inputs.release_type }}"
          
          # Split version into components
          IFS='.' read -r -a VERSION_PARTS <<< "$PREV_VERSION"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"
          
          # Generate new version based on bump type
          case "$BUMP_TYPE" in
            major)
              VERSION="$((MAJOR + 1)).0.0"
              ;;
            minor)
              VERSION="$MAJOR.$((MINOR + 1)).0"
              ;;
            patch)
              VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
              ;;
          esac
          
          # Add release type suffix if needed
          if [ "$RELEASE_TYPE" = "beta" ]; then
            VERSION="${VERSION}-beta"
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Create feature branch for the pre-release
      - name: Create release branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b "release-v${{ steps.version.outputs.VERSION }}"
          git commit --allow-empty -m "Beta testing branch for v${{ steps.version.outputs.VERSION }}"
          git push -u origin "release-v${{ steps.version.outputs.VERSION }}"

      # Run tests to ensure quality
      - name: Run tests
        run: uv run pytest

      # Build package for PyPI
      - name: Build package
        run: uv build

      # Get last tag
      - name: Get last tag
        id: last_tag
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_OUTPUT

      # Create PR for review
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Pre-release v${{ steps.version.outputs.VERSION }}"
          title: "Pre-release v${{ steps.version.outputs.VERSION }}"
          body: |
            Pre-release version bump and documentation updates.
            
            Changes:
            - Built package
            - No version update in main branch in pyproject.toml for pre-release
            - No documentation updates in main branch required for pre-release
          branch: "release-v${{ steps.version.outputs.VERSION }}"
          base: main
          draft: true 

      # Generate changelog
      - name: Generate changelog
        run: |
          # Create new changelog entry
          {
            echo "## [${{ steps.version.outputs.VERSION }}] - $(date +%Y-%m-%d)"
            echo ""
            if [ -n "${{ steps.last_tag.outputs.LAST_TAG }}" ]; then
              git log --graph --format="%h %s" "${{ steps.last_tag.outputs.LAST_TAG }}..HEAD"
            else
              git log --graph --format="%h %s"
            fi
            echo ""
          } > CHANGELOG.md.new

          # If CHANGELOG.md exists, prepend new content
          if [ -f CHANGELOG.md ]; then
            # Get the header (everything before the first ##)
            sed -n '1,/^##/p' CHANGELOG.md | sed '$d' > CHANGELOG.md.tmp
            # Add the new version section
            cat CHANGELOG.md.new >> CHANGELOG.md.tmp
            # Add the rest of the existing content (everything after the first ##)
            sed -n '/^##/,$p' CHANGELOG.md >> CHANGELOG.md.tmp
            mv CHANGELOG.md.tmp CHANGELOG.md
          else
            # Create initial changelog if it doesn't exist
            {
              echo "# Changelog"
              echo ""
              echo "All notable changes to this project will be documented in this file."
              echo ""
              echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),"
              echo "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."
              echo ""
              cat CHANGELOG.md.new
            } > CHANGELOG.md
          fi
          rm CHANGELOG.md.new 
