name: Create RC Release Tag

# Trigger on PR merge to main that affects version-related files
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'CHANGELOG.md'
      - 'hello_world/**'

jobs:
  create-tag:
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout code with full history for tag creation
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"
          pip install build

      # Build the package
      - name: Build package
        run: |
          python -m build

      # Run tox tests
      - name: Run tox tests
        run: |
          tox -e py310,py311

      # Extract version from pyproject.toml
      - name: Extract version
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Check if this is an RC version
      - name: Check if version is RC
        run: |
          if [[ ! "$VERSION" =~ rc[0-9]+$ ]]; then
            echo "Not an RC version, skipping tag creation"
            exit 0
          fi

      # Create and push git tag
      - name: Create and push tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "v$VERSION" -m "Release Candidate v$VERSION"
          git push origin "v$VERSION"

      # Create draft GitHub release
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          draft: true
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz 
