name: Create beta Release Branch

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Branch to create beta release from'
        required: true
        default: 'main'
      bump_type:
        description: 'Version bump type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  create-beta-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Check if merge is from beta branch
        id: check_beta
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Manual run: not skipping."
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "is_beta=false" >> $GITHUB_OUTPUT
            echo "clean_branch=manual" >> $GITHUB_OUTPUT
            exit 0
          fi
          COMMIT_MSG=$(git log -1 --pretty=%B)
          SRC_BRANCH=$(echo "$COMMIT_MSG" | grep -oE 'from [^ ]+' | awk '{print $2}')
          CLEAN_BRANCH=$(basename "$SRC_BRANCH")
          echo "Source branch: $CLEAN_BRANCH"
          echo "clean_branch=$CLEAN_BRANCH" >> $GITHUB_OUTPUT
          if [[ -z "$CLEAN_BRANCH" ]] || [[ "$CLEAN_BRANCH" != *beta* ]]; then
            echo "Not a merge from a beta branch. Skipping workflow."
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "is_beta=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "is_beta=true" >> $GITHUB_OUTPUT
          fi

      - name: Extract bump type from source branch or input
        if: steps.check_beta.outputs.skip == 'false'
        id: bump_type
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "bump_type=${{ github.event.inputs.bump_type }}" >> $GITHUB_OUTPUT
          else
            COMMIT_MSG=$(git log -1 --pretty=%B)
            SRC_BRANCH=$(echo "$COMMIT_MSG" | grep -oE 'from [^ ]+' | awk '{print $2}')
            CLEAN_BRANCH=$(basename "$SRC_BRANCH")
            BUMP_TYPE=$(echo "$CLEAN_BRANCH" | grep -oE '(patch|minor|major)' || echo "patch")
            echo "Bump type: $BUMP_TYPE"
            echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
          fi

      - name: Get current version
        if: steps.check_beta.outputs.skip == 'false'
        id: current_version
        run: |
          CURRENT_VERSION=$(grep -Po '^version = "\K[^"]+' pyproject.toml | head -1)
          echo "Extracted version: $CURRENT_VERSION"
          if [[ -z "$CURRENT_VERSION" ]]; then
            echo "Error: Could not extract version from pyproject.toml"
            exit 1
          fi
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Ensure beta version in pyproject.toml (manual run)
        run: |
          CURRENT_VERSION=$(grep -Po '^version = "\K[^"]+' pyproject.toml | head -1)
          # If it doesn't already end with 'beta', add it
          if [[ ! "$CURRENT_VERSION" =~ beta$ ]]; then
            BETA_VERSION="${CURRENT_VERSION}beta"
            sed -i "s/^version = \".*\"/version = \"$BETA_VERSION\"/" pyproject.toml
            echo "Updated version to $BETA_VERSION in pyproject.toml"
          else
            echo "Version already includes beta: $CURRENT_VERSION"
          fi

      - name: Bump version
        if: steps.check_beta.outputs.skip == 'false'
        id: bump_version
        run: |
          BUMP_TYPE="${{ steps.bump_type.outputs.bump_type }}"
          echo "Bump type: $BUMP_TYPE"
          CURRENT_VERSION="${{ steps.current_version.outputs.version }}"
          # Extract numeric part and suffix
          NUMERIC_VERSION=$(echo "$CURRENT_VERSION" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+')
          SUFFIX=$(echo "$CURRENT_VERSION" | sed -E 's/^[0-9]+\.[0-9]+\.[0-9]+//')
          if [[ -z "$NUMERIC_VERSION" ]]; then
            echo "Error: Could not extract numeric version from $CURRENT_VERSION"
            exit 1
          fi
          IFS='.' read -r MAJOR MINOR PATCH <<< "$NUMERIC_VERSION"
          if [[ -z "$MAJOR" || -z "$MINOR" || -z "$PATCH" ]]; then
            echo "Error: Version must have three numeric parts"
            exit 1
          fi
          ORIG_VERSION="$NUMERIC_VERSION$SUFFIX"
          case "$BUMP_TYPE" in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}${SUFFIX}"
          # Only check if the new version is greater if there's no suffix (i.e., not a pre-release)
          if [[ -z "$SUFFIX" ]]; then
            if ! python -c "from packaging import version; assert version.parse('$NEW_VERSION') > version.parse('$CURRENT_VERSION'), 'New version must be greater than current version'"; then
              echo "Error: New version '$NEW_VERSION' is not greater than current version '$CURRENT_VERSION'"
              exit 1
            fi
          fi
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "orig_version=$ORIG_VERSION" >> $GITHUB_OUTPUT

      - name: Set branch name with beta version
        id: set_branch
        run: |
          BETA_VERSION=$(grep -Po '^version = "\K[^"]+' pyproject.toml | head -1)
          echo "branch_name=beta-release-v$BETA_VERSION" >> $GITHUB_OUTPUT

      - name: Create and checkout beta branch
        run: |
          git checkout -b "${{ steps.set_branch.outputs.branch_name }}"
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Update Changelog
        run: |
          NEW_VERSION="${{ steps.bump_version.outputs.new_version }}"
          # Prepare new changelog section
          {
            echo "## $NEW_VERSION (Beta)"
            echo ""
            git log $(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)..HEAD --pretty=format:"- %s"
            echo ""
          } > NEW_CHANGELOG.md

          # Insert after the first line (# Changelog)
          awk 'NR==1{print; system("cat NEW_CHANGELOG.md"); next} 1' CHANGELOG.md > CHANGELOG.md.tmp
          mv CHANGELOG.md.tmp CHANGELOG.md
          rm NEW_CHANGELOG.md
          git add CHANGELOG.md

      - name: Update pyproject.toml version to beta
        run: |
          ORIG_VERSION="${{ steps.bump_version.outputs.orig_version }}"
          NEW_VERSION="${{ steps.bump_version.outputs.new_version }}"
          BUMP_TYPE="${{ steps.bump_type.outputs.bump_type }}"
          NEW_VERSION="${NEW_VERSION}beta"
          sed -i "s/version = \".*\"/version = \"$NEW_VERSION\"/" pyproject.toml
          git add pyproject.toml

      - name: Commit and push changes
        run: |
          git commit -m "Beta release v$(grep -Po '^version = "\K[^"]+' pyproject.toml | head -1)"
          git push origin "${{ steps.set_branch.outputs.branch_name }}"

      - name: Create PR on GitHub
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          NEW_VERSION=$(grep -Po '^version = "\K[^"]+' pyproject.toml | head -1)
          PR_BODY=$(cat .github/PULL_REQUEST_TEMPLATE.md | sed "s/{{RELEASE_SUMMARY}}/Beta release v$NEW_VERSION/")
          gh pr create \
            --title "Beta Release v$NEW_VERSION" \
            --body "$PR_BODY" \
            --base main \
            --head "${{ steps.set_branch.outputs.branch_name }}" \
            --draft
