name: Create Stable Tag

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-tag:
    # Only run if this is a merge from a stable release branch
    if: |
      contains(github.event.head_commit.message, 'Merge pull request') &&
      contains(github.event.head_commit.message, 'Release') &&
      !contains(github.event.head_commit.message, 'beta')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 
        uses: actions/setup-python@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --all-extras --dev

      # Create and push tag
      - name: Create and push tag
        id: create_tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Get version from pyproject.toml
          VERSION=$(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")
          TAG_VERSION="v$VERSION"
          TAG_MESSAGE="Release v$TAG_VERSION"
          
          # Create and push tag
          git tag -a "$TAG_VERSION" -m "$TAG_MESSAGE"
          git push origin "$TAG_VERSION"
          
          # Output the tag for the next step
          echo "tag=$TAG_VERSION" >> $GITHUB_OUTPUT

      # Wait for publish workflow to complete
      - name: Wait for publish workflow
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ steps.create_tag.outputs.tag }}
          check-name: 'Publish Release'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      # Create draft GitHub release
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v$VERSION
          draft: true
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz 
