name: Create Stable Tag

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-tag:
    # Only run if this is a merge from a release branch
    if: |
      contains(github.event.head_commit.message, 'Merge pull request') &&
      contains(github.event.head_commit.message, 'release-v') &&
      !contains(github.event.head_commit.message, 'beta')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --all-extras --dev

      # Get version from commit message
      - name: Get version
        id: get_version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -o 'release-v[0-9.]*' | cut -d'v' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Create and push tag
      - name: Create and push tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

      # Create draft GitHub release
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v$VERSION
          draft: true
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz 
