name: Package Library
permissions:
  contents: write
  id-token: write
on:
  push:
    branches: [ "main" ]
    tags: 
      - "*"
  pull_request:
    branches: [ "main" ]
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Run tests
      run: uv run pytest
    - name: Check test coverage
      run: uv run pytest --cov=hello_world --cov-report=term-missing
    - name: Build the artifact in dist/
      run: uv build
