name: Publish Release

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    tags:
      - 'v*'
      - '!v*beta*'
      - '!beta-v*'
      - '!v*.*beta*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run Tests
        run: uv run pytest --cov=hello_world --cov-report=term-missing --cov-fail-under=80
      - name: Build the artifact in dist/
        run: uv build

      # Get version from tag
      - name: Get version
        id: get_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            # Extract version from tag
            TAG=${GITHUB_REF#refs/tags/}
            # Remove 'v' prefix
            VERSION=${TAG#v}
          else
            # For main branch, just use a placeholder version for validation
            VERSION="0.0.0"
          fi
          echo "version=$VERSION" >> $GITHUB_ENV

      # Only publish and create release if this is a tag push
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*

      # Create GitHub Release
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: "Release v${{ env.version }}"
          body_path: CHANGELOG.md
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
