name: Publish Pre-release

# Trigger on PR merge to main that affects version-related files
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'CHANGELOG.md'
      - 'releasenotes/**'

jobs:
  publish:
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout code without history to speed up workflow
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install build dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Extract version from pyproject.toml
      - name: Get version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Check if this is a pre-release version
      - name: Check if pre-release
        id: check_prerelease
        run: |
          if [[ "${{ steps.get_version.outputs.VERSION }}" == *"beta"* ]] || [[ "${{ steps.get_version.outputs.VERSION }}" == *"alpha"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      # Build package for PyPI
      - name: Build package
        if: steps.check_prerelease.outputs.is_prerelease == 'true'
        run: python -m build

      # Publish to PyPI
      # Note: Pre-releases are only published to PyPI, not TestPyPI
      # This allows users to test with real package names
      - name: Publish to PyPI
        if: steps.check_prerelease.outputs.is_prerelease == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/* 
