name: Publish Release Candidate

# Trigger on closed pull requests
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  validate-and-publish:
    # Only run if PR was merged (not just closed) and is a release PR
    if: |
      github.event.pull_request.merged == true && 
      contains(github.event.pull_request.title, 'Release Candidate')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Extract version from pyproject.toml
      - name: Get version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Check if this is a release candidate version
      - name: Check if release candidate
        id: check_rc
        run: |
          if [[ "${{ steps.get_version.outputs.VERSION }}" == *"rc"* ]]; then
            echo "is_rc=true" >> $GITHUB_OUTPUT
          else
            echo "is_rc=false" >> $GITHUB_OUTPUT
          fi

      # Build package for PyPI
      - name: Build package
        if: steps.check_rc.outputs.is_rc == 'true'
        run: python -m build

      # Publish to TestPyPI
      - name: Publish to TestPyPI
        if: steps.check_rc.outputs.is_rc == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --repository testpypi dist/*

      # Create GitHub Release
      # Note: RCs get GitHub releases marked as pre-release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release Candidate v${{ steps.get_version.outputs.VERSION }}"
          body_path: CHANGELOG.md
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
