name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build the artifact in dist/
        run: |
          uv build
          ls -l dist/

      - name: Create .pypirc
        env:
          PYPIRC_PATH: ${{ github.workspace }}/.pypirc
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "[pypi]" > "$PYPIRC_PATH"
          echo "  username = __token__" >> "$PYPIRC_PATH"
          echo "  password = $TWINE_PASSWORD" >> "$PYPIRC_PATH"

      - name: Publish to TestPyPI
        if: contains(github.event.inputs.tag_name || github.ref_name, 'beta')
        run: |
          pip install uv
          ls -l dist/
          uv publish dist/* -- --repository-url https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: ${{ !contains(github.event.inputs.tag_name, 'beta') }}
        env:
          PYPIRC_PATH: ${{ github.workspace }}/.pypirc
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install uv
          uv publish dist/* -- --config-file $PYPIRC_PATH

