name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build the artifact in dist/
        run: |
          uv build
          ls -l dist/

      - name: Print working directory and dist contents
        run: |
          pwd
          ls -l
          ls -l dist/

      - name: Publish to TestPyPI
        if: contains(github.event.inputs.tag_name, 'beta')
        run: |
          pip install uv
          uv publish --repository-url https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: ${{ !contains(github.event.inputs.tag_name, 'beta') }}
        run: |
          pip install uv
          uv publish

