name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to release'
        required: false
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          pip install build
          python -m build
      - name: Set tag name
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
      - name: Release to Github
        if: startsWith(github.ref, 'refs/tags/')

        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: ${{ contains(github.ref, 'beta') }}
          prerelease: ${{ contains(github.ref, 'beta') }}
          name: ${{ contains(github.ref, 'beta') && format('Beta Release {0}', github.ref_name) || github.ref_name }}
          body: ${{ contains(github.ref, 'beta') && 'This is a beta release and is not production ready.' || '' }}

      - name: Publish to TestPyPI
        if: contains(github.ref, 'beta')
        run: |
          pip install uv
          uv publish --repository-url https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: ${{ !contains(github.ref, 'beta') }}
        run: |
          pip install uv
          uv publish
