name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to release'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Release Draft to Github
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            dist/*.whl
            dist/*.tar.gz
          draft: ${{ contains(github.event.inputs.tag_name, 'beta') }}
          prerelease: ${{ contains(github.event.inputs.tag_name, 'beta') }}
          name: ${{ contains(github.event.inputs.tag_name, 'beta') && format('{0}', github.event.inputs.tag_name) || github.event.inputs.tag_name }}
          body: ${{ contains(github.event.inputs.tag_name, 'beta') && 'This is a beta release and is not production ready.' || '' }}

      - name: Publish to TestPyPI
        if: contains(github.event.inputs.tag_name, 'beta')
        run: |
          pip install uv
          uv publish -- --repository-url https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: ${{ !contains(github.event.inputs.tag_name, 'beta') }}
        run: |
          pip install uv
          uv publish
