name: Manual Release

permissions:
  contents: write
  id-token: write
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to release'
        required: true
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: 
      name: testpypi
      url: https://test.pypi.org/project/bjones-testing-actions

    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Build the artifact in dist/
        run: |
          uv build
          ls -l dist/
      - name: Release to Github
        if: contains(github.event.inputs.tag_name || github.ref_name, 'beta')

        uses: softprops/action-gh-release@v2
        with:
            tag_name: ${{ github.ref_name }}

            files: | 
              dist/*.whl
              dist/*.tar.gz
            token: ${{ secrets.GH_PAT }}

      - name: Publish to TestPyPI
        if: contains(github.event.inputs.tag_name || github.ref_name, 'beta')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      - name: Publish to PyPI
        if: ${{ !contains(github.event.inputs.tag_name || github.ref_name, 'beta') }}
        uses: pypa/gh-action-pypi-publish@release/v1

        with:
          repository-url: https://test.pypi.org/legacy/
  
  