name: Package Library
permissions:
  contents: write
  id-token: write
on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: pub-hk-ubuntu-24.04-ip
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 
        uses: actions/setup-python@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build the artifact in dist/
        run: |
          uv build
          ls -l dist/  
      - name: Run tox
        run: tox

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: List dist files
        run: ls -l dist/ 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Publish to TestPyPI
        if: ${{ contains(github.ref, 'refs/tags/') }}
        run: |
          pip install uv
          uv publish -- --repository-url https://test.pypi.org/legacy/
      - name: Publish to PyPI
        if: ${{ !contains(github.ref, 'refs/tags/') }}
        run: |
          pip install uv
          uv publish
